name: push-info

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # UTC（国际标准时间）0时0分，北京+8小时 ，代表北京时间上午8时0分

jobs:
  run-coupons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.19.1"

      - name: Install Dependencies
        run: |
          npm install axios moment

      - name: Run Script
        run: node ./index.js
